// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType";

export type AccountPoolMember = { id: string, email: string | null, planType: PlanType | null, active: boolean, unavailableReason: string | null, regularRemaining: bigint | null, sparkRemaining: bigint | null, lastError: string | null, };
