// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ApiCatalogToolSource } from "./ApiCatalogToolSource";

export type ApiCatalogTool = { name: string, source: ApiCatalogToolSource, invocation: string, description: string, inputSchema: JsonValue, outputSchema: JsonValue | null, };
