// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCatalogSection } from "./ApiCatalogSection";
import type { McpServerStatusDetail } from "./McpServerStatusDetail";

export type ApiCatalogReadParams = {
/**
 * Optional subset of catalog sections to return. Omitted returns every section.
 */
include?: Array<ApiCatalogSection> | null,
/**
 * Controls MCP inventory detail. Defaults to `Full` when omitted.
 */
mcpDetail?: McpServerStatusDetail | null, };
