// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiCatalogMethod } from "./ApiCatalogMethod";
import type { ApiCatalogTool } from "./ApiCatalogTool";
import type { ApiCatalogWorkflowRuntime } from "./ApiCatalogWorkflowRuntime";
import type { McpServerStatus } from "./McpServerStatus";
import type { WorkflowSummary } from "./WorkflowSummary";

export type ApiCatalogReadResponse = { schemaVersion: number, generatedAt: bigint, appServerMethods: Array<ApiCatalogMethod>, mcpServers: Array<McpServerStatus>, builtInTools: Array<ApiCatalogTool>, workflowRuntime: ApiCatalogWorkflowRuntime, workflows: Array<WorkflowSummary>, };
