// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ArtifactSourceInfo } from "./ArtifactSourceInfo";

export type ArtifactStateRegisterParams = { namespace: string, scopeKey: string, sourceKey: string, stateDir: string, sources: Array<ArtifactSourceInfo>, metadata: JsonValue, };
