// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type ArtifactStateInfo = { id: bigint, namespace: string, scopeKey: string, sourceKey: string, stateDir: string, metadata: JsonValue, createdAtUnixSec: bigint, updatedAtUnixSec: bigint, lastHitAtUnixSec: bigint | null, };
