// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactFileInfo } from "./ArtifactFileInfo";
import type { ArtifactStateInfo } from "./ArtifactStateInfo";

export type ArtifactFileMatchInfo = { state: ArtifactStateInfo, file: ArtifactFileInfo, };
