// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptBlockMode } from "./PromptBlockMode";

export type DeveloperPromptBlocks = { permissions: PromptBlockMode | null, collaborationMode: PromptBlockMode | null, memories: PromptBlockMode | null, apps: PromptBlockMode | null, skills: PromptBlockMode | null, plugins: PromptBlockMode | null, commitAttribution: PromptBlockMode | null, personality: PromptBlockMode | null, realtime: PromptBlockMode | null, };
