// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperPromptBlocks } from "./DeveloperPromptBlocks";
import type { InstructionPolicy } from "./InstructionPolicy";

export type DeveloperPromptPolicy = { instructions: InstructionPolicy | null, blocks: DeveloperPromptBlocks | null, };
