// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecated legacy notification for `apply_patch` textual output.
 *
 * The server still emits this for approved `apply_patch` completions to
 * preserve compatibility with older clients.
 */
export type FileChangeOutputDeltaNotification = { threadId: string, turnId: string, itemId: string, delta: string, };
