// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowReleaseIdentity } from "./WorkflowReleaseIdentity";
import type { WorkflowUpdatePolicy } from "./WorkflowUpdatePolicy";

export type ManagedWorkflowInfo = { source: string, installed: WorkflowReleaseIdentity, policy: WorkflowUpdatePolicy, dismissedRelease: WorkflowReleaseIdentity | null, };
