// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeveloperPromptPolicy } from "./DeveloperPromptPolicy";
import type { InstructionPolicy } from "./InstructionPolicy";
import type { PromptContextPreset } from "./PromptContextPreset";
import type { UserContextPromptPolicy } from "./UserContextPromptPolicy";

export type PromptContextPolicy = { preset: PromptContextPreset | null, systemInstructions: InstructionPolicy | null, developer: DeveloperPromptPolicy | null, userContext: UserContextPromptPolicy | null, strict: boolean, };
