// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoCiIssueType = "correctness" | "reliability" | "performance" | "scalability" | "security" | "maintainability" | "testability" | "observability" | "compatibility" | "uxConfigCli";
