// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoCiStatusNotification = { threadId: string, phase: string, state: string, scope: string, attempt: number | null, maxAttempts: number | null, message: string, };
