// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewScopePullRequest = { number: number, url: string,
/**
 * Display name of the pull request's base branch, when supplied by GitHub.
 */
baseBranch: string | null,
/**
 * Exact local or remote ref for the pull request base, when it resolved unambiguously.
 */
baseBranchTarget: string | null, };
