// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewScopeBranch = {
/**
 * Human-readable branch name presented to the user.
 */
displayName: string,
/**
 * Exact local or remote ref used as the review target.
 */
target: string, };
