// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewAction } from "./ReviewAction";
import type { ReviewDelivery } from "./ReviewDelivery";
import type { ReviewTarget } from "./ReviewTarget";
import type { ReviewVerification } from "./ReviewVerification";

export type ReviewStartParams = { threadId: string, target: ReviewTarget,
/**
 * Where to run the review: inline (default) on the current thread or
 * detached on a new thread (returned in `reviewThreadId`).
 */
delivery?: ReviewDelivery | null,
/**
 * Whether to verify discovery candidates in a second isolated stage.
 */
verification?: ReviewVerification | null,
/**
 * What to do after the report is ready.
 */
action?: ReviewAction | null, };
