// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewScopeBranch } from "./ReviewScopeBranch";
import type { ReviewScopeCommit } from "./ReviewScopeCommit";
import type { ReviewScopePullRequest } from "./ReviewScopePullRequest";

export type ReviewResolveScopeResponse = {
/**
 * Whether reviews can run on the selected executor with the server's active sandbox setup.
 */
reviewExecutionAvailable: boolean,
/**
 * Short diagnostic when review execution is unavailable.
 */
reviewUnavailableReason: string | null,
/**
 * Whether Fix actions can use the required workspace-write profile on the server.
 */
fixExecutionAvailable: boolean,
/**
 * Short diagnostic when Fix actions are unavailable.
 */
fixUnavailableReason: string | null,
/**
 * Whether the server supports the isolated Double-check stage.
 */
doubleCheckAvailable: boolean,
/**
 * Whether the server supports the whole-repository review target.
 */
wholeRepositoryAvailable: boolean,
/**
 * Open pull request associated with the selected checkout, when one was found.
 */
pullRequest: ReviewScopePullRequest | null,
/**
 * Detected repository default branch, when one was found.
 */
defaultBranch: ReviewScopeBranch | null,
/**
 * Currently checked-out branch, or `null` for a detached head or non-repository cwd.
 */
currentBranch: string | null,
/**
 * Available explicit base-branch targets, with the preferred target first.
 */
branches: Array<string>,
/**
 * Whether staged, unstaged, or untracked changes are present.
 */
hasUncommittedChanges: boolean,
/**
 * Recent commits reachable from HEAD, capped at 100 entries.
 */
commits: Array<ReviewScopeCommit>,
/**
 * Short diagnostic shown when Git repository detection failed.
 */
error: string | null, };
