// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadModelRouterSessionConfigSetParams = { threadId: string,
/**
 * Null clears the session override and returns to repo/user config.
 */
enabled?: boolean | null, };
