// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoCiIssueType } from "./RepoCiIssueType";
import type { RepoCiSessionMode } from "./RepoCiSessionMode";

export type ThreadRepoCiSessionConfigSetParams = { threadId: string,
/**
 * Null clears the session override and returns to repo/user config.
 */
mode?: RepoCiSessionMode | null,
/**
 * Null clears the session override and returns to repo/user config.
 */
issueTypes?: Array<RepoCiIssueType> | null,
/**
 * Null clears the session override and returns to repo/user config.
 */
reviewRounds?: number | null,
/**
 * Null clears the session override and returns to repo/user config.
 */
longCi?: boolean | null, };
