// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImplementMode } from "./ImplementMode";
import type { RepoCiIssueType } from "./RepoCiIssueType";
import type { RepoCiSessionMode } from "./RepoCiSessionMode";

export type ThreadRepoCiSessionConfigSetParams = { threadId: string,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
mode?: RepoCiSessionMode | null | null,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
issueTypes?: Array<RepoCiIssueType> | null | null,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
reviewRounds?: number | null | null,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
longCi?: boolean | null | null,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
implementEnabled?: boolean | null | null,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
implementMode?: ImplementMode | null | null,
/**
 * Omit to leave unchanged; null clears the session override and returns to repo/user config.
 */
implementMaxCycles?: number | null | null, };
