// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadCompactStartSource } from "./ThreadCompactStartSource";

export type ThreadCompactStartParams = { threadId: string,
/**
 * Identifies what initiated the compaction. Omission defaults to manual.
 */
source?: ThreadCompactStartSource | null, };
