// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type ThreadWorkflowCommandParams = { threadId: string,
/**
 * Directory containing the workflow package.
 */
workflowDir: string,
/**
 * Structured workflow input. Must be a JSON object.
 */
input: JsonValue, };
