// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpToolPolicy } from "./McpToolPolicy";
import type { ToolRouterPolicy } from "./ToolRouterPolicy";
import type { ToolSetPolicy } from "./ToolSetPolicy";

export type ToolPolicy = { builtins: ToolSetPolicy | null, mcp: McpToolPolicy | null, dynamic: ToolSetPolicy | null, toolRouter: ToolRouterPolicy | null, };
