// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolInvocationPolicyMode } from "./ToolInvocationPolicyMode";
import type { ToolInvocationRule } from "./ToolInvocationRule";

export type ToolInvocationPolicy = { mode: ToolInvocationPolicyMode, rules: Array<ToolInvocationRule>, };
