// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolSetPolicy = { "mode": "inherit" } | { "mode": "none" } | { "mode": "allowOnly", tools: Array<string>, } | { "mode": "deny", tools: Array<string>, };
