// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolInvocationMcpSelector } from "./ToolInvocationMcpSelector";
import type { ToolInvocationRuleCondition } from "./ToolInvocationRuleCondition";
import type { ToolInvocationRuleEffect } from "./ToolInvocationRuleEffect";

export type ToolInvocationRule = { id: string | null, effect: ToolInvocationRuleEffect, tools: Array<string>, mcp: ToolInvocationMcpSelector | null, when: ToolInvocationRuleCondition | null, message: string | null, };
