// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoCiIssueType } from "./RepoCiIssueType";
import type { RepoCiSessionMode } from "./RepoCiSessionMode";

export type TurnRepoCiConfigParams = { mode?: RepoCiSessionMode | null | null, issueTypes?: Array<RepoCiIssueType> | null | null, reviewRounds?: number | null | null, longCi?: boolean | null | null, };
