// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptBlockMode } from "./PromptBlockMode";

export type UserContextBlocks = { agentsMd: PromptBlockMode | null, environment: PromptBlockMode | null, subagents: PromptBlockMode | null, };
