// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructionPolicy } from "./InstructionPolicy";
import type { UserContextBlocks } from "./UserContextBlocks";

export type UserContextPromptPolicy = { instructions: InstructionPolicy | null, blocks: UserContextBlocks | null, };
