// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowConfigValues = { search_paths: Array<string>, default_location: string, repair_mode: string, max_repair_cycles: number, dependency_update_policy: string, commit_policy: string, validation_profile: string, };
