// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRootInfo } from "./WorkflowRootInfo";
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowListResponse = { roots: Array<WorkflowRootInfo>, workflows: Array<WorkflowSummary>, };
