// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowRunApprovalHandling } from "./WorkflowRunApprovalHandling";

export type WorkflowRunStartParams = { id: string, input?: JsonValue | null, threadId?: string | null, stageSessionId?: string | null, approvalHandling?: WorkflowRunApprovalHandling | null, };
