// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowThreadStatus } from "./WorkflowThreadStatus";

export type WorkflowChildStatus = { workflowName: string, workflowStatus: string, threads: Array<WorkflowThreadStatus>, };
