// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowValidationCommandResult = { command: string, succeeded: boolean, exitCode: number | null, stdout: string, stderr: string, };
