// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRepairResult } from "./WorkflowRepairResult";
import type { WorkflowSummary } from "./WorkflowSummary";
import type { WorkflowValidationInfo } from "./WorkflowValidationInfo";

export type WorkflowRepairResponse = { message: string, workflow: WorkflowSummary, validation: WorkflowValidationInfo, repair: WorkflowRepairResult, };
