// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

export type WorkflowRun = { id: string, workflowId: string, status: WorkflowRunStatus, threadId: string | null, createdAt: bigint, startedAt: bigint | null, completedAt: bigint | null, output: JsonValue | null, error: string | null, };
