// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRepairAction } from "./WorkflowRepairAction";
import type { WorkflowRepairStopReason } from "./WorkflowRepairStopReason";
import type { WorkflowValidationFindingInfo } from "./WorkflowValidationFindingInfo";

export type WorkflowRepairResult = { mode: string, maxRepairCycles: number, repairCyclesRun: number, changed: boolean, stopReason: WorkflowRepairStopReason, appliedFixes: Array<WorkflowRepairAction>, remainingFindings: Array<WorkflowValidationFindingInfo>, blockedFindings: Array<WorkflowValidationFindingInfo>, unsupportedFindings: Array<WorkflowValidationFindingInfo>, };
