// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowConfigValues } from "./WorkflowConfigValues";
import type { WorkflowRootInfo } from "./WorkflowRootInfo";
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowAuthoringContextPrepareResponse = { roots: Array<WorkflowRootInfo>, workflows: Array<WorkflowSummary>, config: WorkflowConfigValues, };
