// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowCommandOptionHint } from "./WorkflowCommandOptionHint";
import type { WorkflowRootKind } from "./WorkflowRootKind";
import type { WorkflowValidationInfo } from "./WorkflowValidationInfo";

export type WorkflowSummary = { id: string, command: string | null, title: string | null, userDescription: string | null, searchTerms: Array<string>, commandOptionHints: Array<WorkflowCommandOptionHint>, inputSchema: JsonValue | null, rootLabel: string, rootKind: WorkflowRootKind, rootPath: string, path: string, workflowYamlPath: string, mentionTarget: string, validation: WorkflowValidationInfo, repairMode: string, };
