// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowReadResponse = { workflow: WorkflowSummary, workflowYaml: string, readme: string | null, };
