// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowReleaseIdentity } from "./WorkflowReleaseIdentity";
import type { WorkflowUpdateStatus } from "./WorkflowUpdateStatus";

export type WorkflowUpdateEntry = { id: string, status: WorkflowUpdateStatus, release: WorkflowReleaseIdentity | null, dismissed: boolean, error: string | null, };
