// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDevelopLocation } from "./WorkflowDevelopLocation";

export type WorkflowDevelopParams = { description: string, id?: string | null, command?: string | null, title?: string | null, location?: WorkflowDevelopLocation | null, stageSessionId?: string | null, };
