// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedWorkflowInfo } from "./ManagedWorkflowInfo";

export type WorkflowSummary = { id: string, command: string, description: string,
/**
 * A local path on the app-server host.
 */
path: string, managed: ManagedWorkflowInfo | null, };
