// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowMarkdownResultNotification } from "./v2/WorkflowMarkdownResultNotification";
import type { WorkflowProgressNotification } from "./v2/WorkflowProgressNotification";

export type ClientNotification = { "method": "initialized" } | { "method": "workflow/progress", "params": WorkflowProgressNotification } | { "method": "workflow/reportToUserMarkdown", "params": WorkflowMarkdownResultNotification };
